services:
  fastapi:
    build: .
    container_name: fraud_api
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - prometheus

  streamlit:
    build: .
    container_name: streamlit_ui
    command: streamlit run streamlit_app.py --server.port 8501 --server.enableCORS false
    ports:
      - "8501:8501"
    depends_on:
      - fastapi

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.sendgrid.net:587
      - GF_SMTP_USER=${SMTP_USER}
      - GF_SMTP_PASSWORD=${SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=sattineehar0@gmail.com
      - GF_SMTP_SKIP_VERIFY=true
    volumes:
      - grafana-data:/var/lib/grafana

  data_sender:
    build:
      context: .
      dockerfile: Dockerfile.sender
    container_name: synthetic_data_sender
    depends_on:
      - fastapi

volumes:
  grafana-data:
